### ISSUE TITLE
How to calculate lossb ？

### ISSUE THREAD

**Issue by Lunarli** [foryichuanqi/Paper2022.09-Remaining-useful-life-prediction-by-TaFCN#2]
In your paper you said ：
![image](https://user-images.githubusercontent.com/49749330/203464305-64a5e66c-7233-4443-abd2-2a4c461b6a9c.png)
and x  was an independent variable
But in you sharing code：
![image](https://user-images.githubusercontent.com/49749330/203464437-cd084713-786c-485f-864a-96ba23de9d81.png)
**The lossb was only related to the ytrue label**
Did I misunderstand?  What exactly does x mean?

**Comment by foryichuanqi** [comment]
Exactly. The lossb was only related to the ytrue label. ![Uploading image.png…]()get min value when x=0.5*A.

**Comment by foryichuanqi** [comment]
Exactly. The lossb was only related to the ytrue label. 
lossb get min value of the () of Eq.(1) when x=0.5*A.



> In your paper you said ： ![image](https://user-images.githubusercontent.com/49749330/203464305-64a5e66c-7233-4443-abd2-2a4c461b6a9c.png) and x was an independent variable But in you sharing code： ![image](https://user-images.githubusercontent.com/49749330/203464437-cd084713-786c-485f-864a-96ba23de9d81.png) **The lossb was only related to the ytrue label** Did I misunderstand? What exactly does x mean?

Exactly. The lossb was only related to the ytrue label. 
lossb get min value of the () of Eq.(1) when x=0.5*A.

**Comment by Lunarli** [comment]
Thanks! I got it!&nbsp;I'm just wondering what x stood for when I saw&nbsp;Eq.(1) in&nbsp;your paper. Actually，The lossb was the standard deviation of ytrue and independent of min function.
BTW，your sharing code is pretty well. It has a complete structure and is very kind to reproduce.
 Thanks for sharing it !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "foryichuanqi/Paper2022-Remaining-useful-life-prediction-by-TaFCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 中午11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [foryichuanqi/Paper2022-Remaining-useful-life-prediction-by-TaFCN] How to calculate lossb ？ (Issue #2)





 
Exactly. The lossb was only related to the ytrue label. get min value when x=0.5*A.
